name: build-release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 8
        uses: actions/setup-java@master
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  release:
    if: contains(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@master
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Extract version from commit message
        id: extract_version
        run: |
          # Ensure the commit message follows the 'Release vX.Y.Z' format.
          VERSION=$(echo "${{ github.event.head_commit.message }}" | sed -nE 's/.*Release (v[0-9]+\.[0-9]+\.[0-9]+).*/\1/p')
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Build project
        run: ./gradlew build
      - name: Create or Update Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          name: BingoSplashCN (${{ env.version }})
          body: |
            ## Release Notes
            - **Version**: ${{ env.version }}
            - **Date**: ${{ github.event.head_commit.timestamp }}
            - **Changelog**: [Compare Changes](https://github.com/ATRI-BOT-P/ATRI-BOT/compare/${{ github.event.before }}...${{ github.sha }})
          draft: false
          prerelease: false
          files: |
            build/libs/*
