name: BingoSplashCN Release/Check

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Check code format
        run: ./gradlew check

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Extract version from commit message
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE 'Release v[0-9]+\.[0-9]+\.[0-9]+' | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create or Update Release
        if: env.version != ''
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          name: BingoSplashCN Release ${{ env.version }}
          body: |
            **Full Changelog**: [Compare Changes](https://github.com/ATRI-BOT-P/BingoSplashCN/compare/${{ github.event.before }}...${{ github.sha }})
          draft: false
          prerelease: false
          files: |
            build/libs/*
