name: gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  release:
    if: contains(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Get current tag
        id: get_version
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "current_tag=$TAG" >> $GITHUB_ENV
      - name: Calculate next tag
        id: calculate_tag
        run: |
          CURRENT_TAG="${{ env.current_tag }}"
          if [[ "$CURRENT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            BASE_VERSION=$(echo "$CURRENT_TAG" | cut -d 'v' -f 2)
            MAJOR=$(echo "$BASE_VERSION" | cut -d '.' -f 1)
            MINOR=$(echo "$BASE_VERSION" | cut -d '.' -f 2)
            PATCH=$(echo "$BASE_VERSION" | cut -d '.' -f 3)
            NEXT_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          else
            NEXT_TAG="v0.0.1"
          fi
          while git rev-parse "$NEXT_TAG" >/dev/null 2>&1; do
            PATCH=$(echo "$NEXT_TAG" | cut -d '.' -f 3)
            NEXT_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          done
          echo "tag=$NEXT_TAG" >> $GITHUB_ENV
      - name: Build project
        run: ./gradlew build
      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          name: Forge 1.8.9 Build ${{ env.tag }}
          body: |
            **Full Changelog**: https://github.com/your_repo/compare/${{ env.current_tag }}...${{ env.tag }}
          draft: false
          prerelease: false
          files: |
            build/libs/*
